ALTER TABLE jobs ADD COLUMN IF NOT EXISTS anunciante TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS status_anunciante BOOLEAN DEFAULT FALSE;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS application_link TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS application_text TEXT;
